### ISSUE TITLE
CourseSmart stitcher program won't open in Windows 7

### ISSUE THREAD

**Issue by applyants** [SpikedCola/DownloadCourseSmartBooks#8]
When I double click "CourseSmart Stitcher.exe" I get the following error message from windows:
![csmart_stitch_error](https://cloud.githubusercontent.com/assets/10954245/6143159/48a38af4-b189-11e4-8531-9932ef6ba393.jpg)

https://github.com/SpikedCola/DownloadCourseSmartBooks/tree/master/source/CourseSmart%20Stitcher

Do I need a different version of Windows?  I'm running Windows 7 in Parallels on OS X Mavericks.

**Comment by ian5142** [comment]
Just do a quick Google search: flash.ocx missing Windows 7

**Comment by applyants** [comment]
Oh, ok cool. Thanks.  Looks like I just needed to update flash.  Sorry, fairly Windows illiterate.
